// generated by stringer -type=attrClass; DO NOT EDIT

package main

import "fmt"

const _attrClass_name = "attrClassBuiltinattrClassTimeattrClassSliceattrClassMapattrClassStruct"

var _attrClass_index = [...]uint8{16, 29, 43, 55, 70}

func (i attrClass) String() string {
	if i < 0 || i >= attrClass(len(_attrClass_index)) {
		return fmt.Sprintf("attrClass(%d)", i)
	}
	hi := _attrClass_index[i]
	lo := uint8(0)
	if i > 0 {
		lo = _attrClass_index[i-1]
	}
	return _attrClass_name[lo:hi]
}
