// generated by stringer -type=persistenceClass; DO NOT EDIT

package main

import "fmt"

const _persistenceClass_name = "persistenceClassPersistentpersistenceClassNonPersistentpersistenceClassEphemeral"

var _persistenceClass_index = [...]uint8{26, 55, 80}

func (i persistenceClass) String() string {
	if i < 0 || i >= persistenceClass(len(_persistenceClass_index)) {
		return fmt.Sprintf("persistenceClass(%d)", i)
	}
	hi := _persistenceClass_index[i]
	lo := uint8(0)
	if i > 0 {
		lo = _persistenceClass_index[i-1]
	}
	return _persistenceClass_name[lo:hi]
}
