package main

import (
	"bytes"
	"fmt"
	"go/format"
	"io/ioutil"
	"path/filepath"
)

type writer struct {
	pkg      string
	typename string
	buf      bytes.Buffer
}

func newWriter(pkg string, typename string) *writer {
	w := writer{pkg: pkg, typename: typename}
	w.printf(`
//
// AUTO-GENERATED by metago. DO NOT EDIT!
//

`)
	w.printf("package %s\n\n", filepath.Base(pkg))
	return &w
}

func (w *writer) printf(format string, args ...interface{}) {
	fmt.Fprintf(&w.buf, format, args...)
}

func (w *writer) close() error {
	buf, err := format.Source(w.buf.Bytes())
	if err != nil {
		return fmt.Errorf("couldn't format generated src: %s", err)
	}
	fn := filepath.Join(w.pkg, fmt.Sprintf("%s.go", w.typename))
	if !isChanged(buf, fn) {
		return nil
	}
	return ioutil.WriteFile(fn, buf, 0755)
}

func isChanged(n []byte, fn string) bool {
	o, err := ioutil.ReadFile(fn)
	if err != nil {
		return true
	}
	return bytes.Equal(o, n)
}
