//
// AUTO-GENERATED by metago. DO NOT EDIT!
//

package test

import (
	"github.com/idawes/metago"
	"github.com/nu7hatch/gouuid"
)

var MetagoPackageUUID uuid.UUID

func init() {
	id, _ := uuid.ParseHex("2ddeafcf-0764-545c-6e7b-047e00947709")
	MetagoPackageUUID = *id
}

var BasicAttrTypesObjectID = metago.TypeID{Pkg: &MetagoPackageUUID, Typ: 1}
var ExtendedObjectID = metago.TypeID{Pkg: &MetagoPackageUUID, Typ: 2}
var SliceTestObjectID = metago.TypeID{Pkg: &MetagoPackageUUID, Typ: 3}
var StructTestObjectID = metago.TypeID{Pkg: &MetagoPackageUUID, Typ: 4}
