//
// AUTO-GENERATED by metago. DO NOT EDIT!
//

package test

var MetagoPackageUUID = uuid.ParseHex("2ddeafcf-0764-545c-6e7b-047e00947709")

var StructTestObjectID = TypeID{pkg: MetagoPackageUUID, typ: 4}
var BasicAttrTypesObjectID = TypeID{pkg: MetagoPackageUUID, typ: 1}
var ExtendedObjectID = TypeID{pkg: MetagoPackageUUID, typ: 2}
var SliceTestObjectID = TypeID{pkg: MetagoPackageUUID, typ: 3}
