//
// AUTO-GENERATED by metago. DO NOT EDIT!
//

package test

import (
	"github.com/idawes/metago"
)

type StructTestObject struct {
	B BasicAttrTypesObject
}

func (o1 *StructTestObject) Equals(o2 *StructTestObject) bool {

	{
		va, vb := o1.B, o2.B
		if va.Equals(&vb) {
			return false
		}
	}
	return true
}

func (o1 *StructTestObject) Diff(o2 *StructTestObject) *metago.Diff {
	d := &metago.Diff{}

	{
		va, vb := o1.B, o2.B
		d.Changes = append(d.Changes, metago.NewStructChg(&StructTestObjectBSREF, va.Diff(&vb)))
	}
	return d
}
