//
// AUTO-GENERATED by metago. DO NOT EDIT!
//

package test

import (
	"github.com/idawes/metago"
)

type StructTestObject struct {
	B BasicAttrTypesObject
}

func (o1 *StructTestObject) Equals(o2 *StructTestObject) bool {

	if o1.B != o2.B {
		return false
	}
	return true
}

func (o1 *StructTestObject) Diff(o2 *StructTestObject) (d *metago.Diff) {

	if o1.B != o2.B {
		d.Add(NewBasicAttrTypesObjectDiff(AID_StructTestObject_B, true, o1.B, o2.B))
	}
	return true
}
