// generated by stringer -type=ChangeType; DO NOT EDIT

package metago

import "fmt"

const _ChangeType_name = "ChangeTypeInsertChangeTypeDeleteChangeTypeModify"

var _ChangeType_index = [...]uint8{0, 16, 32, 48}

func (i ChangeType) String() string {
	if i < 0 || i+1 >= ChangeType(len(_ChangeType_index)) {
		return fmt.Sprintf("ChangeType(%d)", i)
	}
	return _ChangeType_name[_ChangeType_index[i]:_ChangeType_index[i+1]]
}
