// generated by stringer -type=PersistenceClass; DO NOT EDIT

package metago

import "fmt"

const _PersistenceClass_name = "PersistenceClassPersistentPersistenceClassNonPersistentPersistenceClassEphemeral"

var _PersistenceClass_index = [...]uint8{26, 55, 80}

func (i PersistenceClass) String() string {
	if i < 0 || i >= PersistenceClass(len(_PersistenceClass_index)) {
		return fmt.Sprintf("PersistenceClass(%d)", i)
	}
	hi := _PersistenceClass_index[i]
	lo := uint8(0)
	if i > 0 {
		lo = _PersistenceClass_index[i-1]
	}
	return _PersistenceClass_name[lo:hi]
}
