// generated by stringer -type=PersistenceClass; DO NOT EDIT

package metago

import "fmt"

const _PersistenceClass_name = "PersistenceClassPersistentPersistenceClassNonPersistentPersistenceClassEphemeral"

var _PersistenceClass_index = [...]uint8{0, 26, 55, 80}

func (i PersistenceClass) String() string {
	if i < 0 || i+1 >= PersistenceClass(len(_PersistenceClass_index)) {
		return fmt.Sprintf("PersistenceClass(%d)", i)
	}
	return _PersistenceClass_name[_PersistenceClass_index[i]:_PersistenceClass_index[i+1]]
}
