// generated by stringer -type=attrClass; DO NOT EDIT

package main

import "fmt"

const _attrClass_name = "ATTR_TYPE_BASICATTR_TYPE_TIMEATTR_TYPE_SLICEATTR_TYPE_MAPATTR_TYPE_STRUCT"

var _attrClass_index = [...]uint8{0, 15, 29, 44, 57, 73}

func (i attrClass) String() string {
	if i+1 >= attrClass(len(_attrClass_index)) {
		return fmt.Sprintf("attrClass(%d)", i)
	}
	return _attrClass_name[_attrClass_index[i]:_attrClass_index[i+1]]
}
