// generated by stringer -type=attrClass; DO NOT EDIT

package main

import "fmt"

const _attrClass_name = "attrClassBuiltinattrClassQualifiedBuiltinattrClassSliceattrClassMapattrClassDiffableObj"

var _attrClass_index = [...]uint8{0, 16, 41, 55, 67, 87}

func (i attrClass) String() string {
	if i < 0 || i+1 >= attrClass(len(_attrClass_index)) {
		return fmt.Sprintf("attrClass(%d)", i)
	}
	return _attrClass_name[_attrClass_index[i]:_attrClass_index[i+1]]
}
