// generated by stringer -type=persistenceClass; DO NOT EDIT

package main

import "fmt"

const _persistenceClass_name = "persistenceClassPersistentpersistenceClassNonPersistentpersistenceClassEphemeral"

var _persistenceClass_index = [...]uint8{0, 26, 55, 80}

func (i persistenceClass) String() string {
	if i < 0 || i+1 >= persistenceClass(len(_persistenceClass_index)) {
		return fmt.Sprintf("persistenceClass(%d)", i)
	}
	return _persistenceClass_name[_persistenceClass_index[i]:_persistenceClass_index[i+1]]
}
